name: 'analytica.click.gh'
description: 'analytica.click GH build step'
author: 'analytica.click'
inputs:
  ANALYTICA_TOKEN:
    required: true
    description: 'your API token'
  GITHUB_CONTEXT:
    required: true
    description: '${{ toJson(github) }}'
runs:
  using: 'node16'
  main: 'dist/index.js'