name: 'analytica.click.gh'
description: 'analytica.click GH build step'
author: 'analytica.click'
inputs:
  ANALYTICA_TOKEN:
    required: true
    description: 'your API token'
  GITHUB_CONTEXT:
    required: false
    description: 'the github context'
    default: '${{ toJson(github) }}'
  JOB_CONTEXT:
    required: false
    description: 'the job context'
    default: '${{ toJson(job) }}'
runs:
  using: 'node16'
  main: 'dist/index.js'