name: 'analytica.click.gh'
description: 'analytica.click GH build step'
author: 'analytica.click'
inputs:
  analyticaToken:
    required: true
    description: 'your API token'
  eventName:
    required: true
    description: 'the event name to track'
runs:
  using: 'node18'
  main: 'dist/index.js'