allowBuilds:
  '@google/genai': false
  ag-common: true
  esbuild: true
  eslint-config-e7npm: true
  protobufjs: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - analytica.click
onlyBuiltDependencies:
  - ag-common
  - esbuild
  - eslint-config-e7npm
  - unrs-resolver
