name: test flow
on:
  workflow_dispatch:
    inputs:
      analyticaToken:
        description: 'api key'
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: test analytica trigger
      uses: andreigecanalytica/analytica.click.gh@1
      with:
        analyticaToken: '${{ github.event.inputs.analyticaToken }}'
        eventName: '${{ github.repository }}/GH/${{ github.job }}/${{ github.event_name }}'