name: test fail
on:
  workflow_dispatch:
    inputs:
      analyticaToken:
        description: 'api key'
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  testFail:
    runs-on: ubuntu-latest
    name: testFail
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: |
        echo "$GITHUB_CONTEXT";
        echo "$JOB_CONTEXT";
        echo "$STEPS_CONTEXT"
    - name: Try to fail
      id: failure
      run: exit 1

    - name: notify analytica of build
      if: always()
      uses: andreigecanalytica/analytica.click.gh@v2
      with:
        ANALYTICA_TOKEN: '${{ secrets.ANALYTICATOKEN }}'