name: test flow
on:
  workflow_dispatch:
    inputs:
      analyticaToken:
        description: 'api key'
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: notify analytica of build
      uses: andreigecanalytica/analytica.click.gh@2
      with:
        ANALYTICA_TOKEN: '${{ secrets.ANALYTICATOKEN }}'